name: Build ExtremeKernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Device codename (e.g., x1slte)'
        required: true
        default: 'x1slte'
      use_ksu:
        description: 'Use KernelSU? (y or n)'
        required: true
        default: 'n'
      use_ccache:
        description: 'Use ccache? (y or n)'
        required: true
        default: 'y'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libarchive-tools ccache bc bison flex build-essential \
            libssl-dev libncurses5-dev libelf-dev rsync wget unzip curl git

      - name: Show system resources (debug)
        run: |
          df -h
          free -h
          ulimit -a

      - name: Setup ccache
        if: ${{ github.event.inputs.use_ccache == 'y' }}
        run: |
          mkdir -p ~/.ccache
          export CCACHE_DIR=~/.ccache
          export USE_CCACHE=1
          ccache -M 10G
          ccache -s

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build kernel
        run: |
          set -euxo pipefail
          # Export single-threaded make to reduce memory issues
          export MAKEFLAGS="-j1"
          # Enable verbose build logging
          ./build.sh -m ${{ github.event.inputs.device }} \
                      -k ${{ github.event.inputs.use_ksu }} \
                      -c ${{ github.event.inputs.use_ccache }} \
                      2>&1 | tee build/build.log

      - name: List produced artifacts
        run: |
          echo "Searching for kernel artifacts..."
          find build/out -type f \( -name "*.zip" -o -name "*.img" \) || echo "No artifacts found"

      - name: Upload kernel zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zip
          path: build/out/**/*.zip
          retention-days: 7

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/build.log
          retention-days: 7
